# @package diffusion

learn_sigma: False
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: False
rescale_learned_sigmas: False
mse_loss_weight_type: "min_snr_5"